using System.Text;
using KatStreamToolkit.Models;

namespace KatStreamToolkit.Services;

public static class RelayConfigGenerator
{
    public static string GenerateNginxConf(AppConfig cfg, bool includeKeys = true)
    {
        var up = cfg.Upstream;
        var sb = new StringBuilder();

        sb.AppendLine("# Generated by KAT's Streaming Toolkit - regenerate from the app after changing destinations.");
        sb.AppendLine("# NOTE: this file contains your platform stream keys. Never commit it publicly.");
        sb.AppendLine("load_module /usr/lib/nginx/modules/ngx_rtmp_module.so;");
        // nginx-rtmp is per-worker: a stream lives inside one worker process, so
        // with 'auto' the /stat endpoint only reports the worker the publisher
        // landed on (the toolkit usually polls a different one and reports "no
        // incoming stream") and exec_pull encoders starve on another worker.
        // One worker handles a full multi-destination restream fine.
        sb.AppendLine("worker_processes 1;");
        sb.AppendLine("error_log /var/log/nginx/error.log warn;");
        sb.AppendLine("pid /run/nginx.pid;");
        sb.AppendLine();
        sb.AppendLine("events {");
        sb.AppendLine("    worker_connections 1024;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("rtmp {");
        sb.AppendLine("    server {");
        sb.AppendLine("        listen 1935;");
        sb.AppendLine("        chunk_size 4096;");
        sb.AppendLine();
        sb.AppendLine("        application live {");
        sb.AppendLine("            live on;");
        sb.AppendLine("            record off;");
        sb.AppendLine("            meta copy;");
        sb.AppendLine("            drop_idle_publisher 30s;");
        sb.AppendLine();

        var passthrough = cfg.Destinations.Where(d => d.Enabled && d.Orientation == Orientation.Landscape && d.PortraitStyle != PortraitStyle.Custom).ToList();
        var processed = cfg.Destinations.Where(d => d.Enabled && (d.Orientation == Orientation.Portrait || d.PortraitStyle == PortraitStyle.Custom)).ToList();

        if (passthrough.Count == 0 && processed.Count == 0)
            sb.AppendLine("            # (no destinations enabled yet - enable some in the toolkit)");

        foreach (var dest in passthrough)
        {
            sb.AppendLine($"            # {dest.Name}");
            // An empty ingest URL must not reach nginx (it would parse as a
            // broken push target); leave a visible placeholder instead.
            if (string.IsNullOrWhiteSpace(dest.IngestUrl))
                sb.AppendLine("            # (skipped: no ingest URL set - paste the RTMP URL from the platform's live-key page, then redeploy)");
            else
                sb.AppendLine($"            push \"{Url(dest, includeKeys)}\";");
            sb.AppendLine();
        }

        foreach (var dest in processed)
        {
            sb.AppendLine($"            # {dest.Name} ({dest.PortraitStyle})");
            if (string.IsNullOrWhiteSpace(dest.IngestUrl))
                sb.AppendLine("            # (skipped: no ingest URL set - paste the RTMP URL from the platform's live-key page, then redeploy)");
            else
                sb.AppendLine($"            exec_push {BuildFfmpegArgs(cfg, dest, includeKeys)};");
            sb.AppendLine();
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("# Local-only health/stats endpoints. docker-compose binds this to the");
        sb.AppendLine("# server's loopback, so the toolkit reads it over SSH and the internet cannot.");
        sb.AppendLine("http {");
        sb.AppendLine("    server {");
        sb.AppendLine("        listen 127.0.0.1:8080;");
        sb.AppendLine();
        sb.AppendLine("        location = /health { return 200 \"kat-relay ok\\n\"; }");
        sb.AppendLine("        location /stat { rtmp_stat all; }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string Url(DestinationConfig dest, bool includeKeys = true)
        => $"{dest.IngestUrl.TrimEnd('/')}/{(includeKeys ? dest.StreamKey : SecretsStore.MaskKey)}";

    // The exact lines this destination contributes to nginx.conf's live application,
    // e.g. for the Output Studio preview. Mirrors GenerateNginxConf byte for byte.
    public static string DescribeDestination(AppConfig cfg, DestinationConfig dest, bool includeKeys = true)
    {
        var sb = new StringBuilder();
        if (string.IsNullOrWhiteSpace(dest.IngestUrl))
        {
            sb.AppendLine($"# {dest.Name}");
            sb.Append("# (skipped: no ingest URL set - paste the RTMP URL from the platform's live-key page, then redeploy)");
            return sb.ToString();
        }
        if (dest.Orientation == Orientation.Portrait || dest.PortraitStyle == PortraitStyle.Custom)
        {
            sb.AppendLine($"# {dest.Name} ({dest.PortraitStyle})");
            sb.Append($"exec_push {BuildFfmpegArgs(cfg, dest, includeKeys)};");
        }
        else
        {
            sb.AppendLine($"# {dest.Name}");
            sb.Append($"push \"{Url(dest, includeKeys)}\";");
        }
        return sb.ToString();
    }

    public static string SnapshotPath(Guid destinationId) => $"/tmp/kat-preview-{destinationId:N}.jpg";

    public static string SnapshotTestPath(Guid destinationId) => $"/tmp/kat-preview-test-{destinationId:N}.jpg";

    // File name (inside the bundle's backgrounds/ folder and the container's
    // /var/kat-backgrounds mount) for a destination's custom background image.
    public static string BackgroundFileName(DestinationConfig dest)
    {
        string ext = Path.GetExtension(dest.CustomBackgroundPath);
        if (string.IsNullOrEmpty(ext)) ext = ".png";
        return dest.Id + ext.ToLowerInvariant();
    }

    public static string BackgroundImageFile(DestinationConfig dest)
        => dest.PortraitStyle == PortraitStyle.Custom && !string.IsNullOrWhiteSpace(dest.CustomBackgroundPath)
            ? $"/var/kat-backgrounds/{BackgroundFileName(dest)}"
            : "";

    public static string OverlayFileName(OutputLayer layer)
    {
        string ext = Path.GetExtension(layer.Path);
        if (string.IsNullOrEmpty(ext)) ext = ".png";
        return $"overlay_{layer.Id}{ext.ToLowerInvariant()}";
    }

    public static string OverlayImageFile(OutputLayer layer)
        => $"/var/kat-backgrounds/{OverlayFileName(layer)}";

    // The destination's exact ffmpeg graph, but fed a synthetic test source and
    // writing only to the test snapshot file: nothing is pushed to any platform.
    public static string BuildTestEncoderCommand(AppConfig cfg, DestinationConfig dest)
        => BuildFfmpegArgs(cfg, dest, includeKeys: true, forTest: true);

    private static string BuildFfmpegArgs(AppConfig cfg, DestinationConfig dest, bool includeKeys, bool forTest = false)
    {
        var up = cfg.Upstream;
        int srcW = Math.Max(2, up.Width);
        int srcH = Math.Max(2, up.Height);
        string pull = $"rtmp://127.0.0.1:1935/live/$name";
        string output = Url(dest, includeKeys);
        int gop = Math.Max(1, up.Fps * Math.Max(1, dest.KeyframeSeconds));
        string preset = string.IsNullOrWhiteSpace(dest.EncoderPreset) ? "veryfast" : dest.EncoderPreset.Trim();
        string audio = $"-c:a aac -b:a {dest.AudioBitrateKbps}k -ar 44100";
        if (dest.DelaySeconds > 0)
            audio += $" -af adelay={dest.DelaySeconds * 1000}:all=1";
        string fps = dest.FpsOverride > 0 ? $" -r {dest.FpsOverride}" : "";
        string video = $"-c:v libx264 -preset {preset} -b:v {dest.VideoBitrateKbps}k -maxrate {dest.VideoBitrateKbps}k -bufsize {dest.VideoBitrateKbps * 2}k -pix_fmt yuv420p -g {gop} -sc_threshold 0{fps}";
        string extra = string.IsNullOrWhiteSpace(dest.ExtraArgs) ? "" : " " + dest.ExtraArgs.Trim();
        string delay = dest.DelaySeconds > 0 ? $",tpad=start_duration={dest.DelaySeconds}" : "";

        // All portrait styles build a filtered graph labelled [v], so the snapshot
        // output can always reference the composed picture.
        string inputs;
        string filterComplex;

        // Portrait outputs are 1080x1920; a landscape Custom layout edits the feed
        // at the upstream resolution instead.
        bool portraitOut = dest.Orientation == Orientation.Portrait;
        int outW = portraitOut ? 1080 : Math.Max(2, MakeEven(srcW));
        int outH = portraitOut ? 1920 : Math.Max(2, MakeEven(srcH));

        if (dest.PortraitStyle == PortraitStyle.CenterCrop)
        {
            var (cropW, cropH, x, y) = ComputeCropRect(srcW, srcH);
            inputs = "";
            filterComplex = $"[0:v]crop={cropW}:{cropH}:{x}:{y},scale={outW}:{outH}:flags=lanczos,setsar=1{delay}[v]";
        }
        else if (dest.PortraitStyle == PortraitStyle.BlurredBackground)
        {
            inputs = "";
            filterComplex =
                "[0:v]split=2[bg][fg];" +
                $"[bg]scale={outW}:{outH}:force_original_aspect_ratio=increase,crop={outW}:{outH},boxblur=20:5[bgb];" +
                $"[fg]scale={outW}:{outH}:force_original_aspect_ratio=decrease:flags=lanczos[fgs];" +
                $"[bgb][fgs]overlay=(W-w)/2:(H-h)/2,setsar=1{delay}[v]";
        }
        else if (dest.Layers.Count > 0)
        {
            BuildLayeredGraph(dest, srcW, srcH, outW, outH, delay, out inputs, out filterComplex);
        }
        else if (portraitOut)
        {
            BuildLegacyCustomGraph(dest, srcW, srcH, delay, out inputs, out filterComplex);
        }
        else
        {
            // Landscape Custom with no layers yet: a plain re-encoded copy.
            inputs = "";
            filterComplex = $"[0:v]scale={outW}:{outH},setsar=1{delay}[v]";
        }

        // The platform push and the preview snapshot both consume the composed
        // video, so split the label: [vmain] feeds the push, [vsnap] the JPEG.
        filterComplex += ";[v]split=2[vmain][vsnap]";
        // `0:a?` = optional mapping: with no audio track in the OBS feed (muted
        // or video-only capture) the old hard `-map 0:a` made ffmpeg exit
        // instantly with "Stream map '0:a' matches no streams", killing every
        // portrait/custom output while landscape pushes kept working.
        string pushMap = "-map \"[vmain]\" -map 0:a?";
        string snap = $" -map \"[vsnap]\" -f image2 -r 2 -update 1 -q:v 5 {SnapshotPath(dest.Id)}";

        if (forTest)
        {
            // Test run: the synthetic source stands in for the OBS feed, so it must
            // be the INPUT resolution (crop math is normalized against it). No
            // audio, nothing pushed - only the test snapshot.
            return $"\"/usr/bin/ffmpeg\" -hide_banner -nostdin -y -loglevel warning -f lavfi -i \"testsrc2=size={srcW}x{srcH}:rate=30\"{inputs} -filter_complex \"{filterComplex}\" -map \"[vmain]\" {video} -f null - -map \"[vsnap]\" -f image2 -r 2 -update 1 -q:v 5 {SnapshotTestPath(dest.Id)}";
        }

        return $"\"/usr/bin/ffmpeg\" -hide_banner -nostdin -y -loglevel warning -i \"{pull}\"{inputs} -filter_complex \"{filterComplex}\" {pushMap} {video} {audio}{extra} -f flv \"{output}\"{snap}";
    }

    // -loop 1 belongs to the image2 demuxer and is ignored by the GIF demuxer,
    // so an animated GIF played exactly once and froze on its last frame.
    // GIFs need -ignore_loop 0 to loop forever instead.
    private static string ImageInputArg(string file)
        => string.Equals(Path.GetExtension(file), ".gif", StringComparison.OrdinalIgnoreCase)
            ? $" -ignore_loop 0 -i \"{file}\""
            : $" -loop 1 -i \"{file}\"";

    // The single-crop custom layout (kept for configs created before layers).
    private static void BuildLegacyCustomGraph(DestinationConfig dest, int srcW, int srcH, string delay, out string inputs, out string filterComplex)
    {
        var (cx, cy, cw, chn, fx, fy, fgs) = NormalizedCustomLayout(dest, srcW, srcH);
        int cropPxW = Math.Min(MakeEven((int)Math.Round(cw * srcW)), FloorEven(srcW));
        int cropPxH = Math.Min(MakeEven((int)Math.Round(cropPxW * 16.0 / 9.0)), FloorEven(srcH));
        int cxPx = Math.Clamp((int)Math.Round(cx * srcW), 0, Math.Max(0, cropPxW <= srcW ? srcW - cropPxW : 0));
        int cyPx = Math.Clamp((int)Math.Round(cy * srcH), 0, Math.Max(0, cropPxH <= srcH ? srcH - cropPxH : 0));
        int fgH = Math.Max(2, MakeEven((int)Math.Round(fgs * 1920)));
        int fgW = Math.Max(2, MakeEven((int)Math.Round(fgH * 9.0 / 16.0)));
        int fxPx = Math.Clamp((int)Math.Round(fx * 1080), 0, Math.Max(0, 1080 - fgW));
        int fyPx = Math.Clamp((int)Math.Round(fy * 1920), 0, Math.Max(0, 1920 - fgH));

        string cropChain = $"crop={cropPxW}:{cropPxH}:{cxPx}:{cyPx}";
        string fgChain = $"scale={fgW}:{fgH}:flags=lanczos";
        string tail = $"[bg][fg]overlay={fxPx}:{fyPx},setsar=1{delay}[v]";
        string bgFile = BackgroundImageFile(dest);
        inputs = string.IsNullOrEmpty(bgFile) ? "" : ImageInputArg(bgFile);
        filterComplex = string.IsNullOrEmpty(bgFile)
            ? $"[0:v]{cropChain},split=2[bs][fs];[bs]scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920,boxblur=20:5[bg];[fs]{fgChain}[fg];{tail}"
            : $"[1:v]scale=1080:1920[bg];[0:v]{cropChain}[c];[c]{fgChain}[fg];{tail}";
    }

    // OBS-style composite: z-ordered source cuts, image overlays, blur areas and
    // background reveals over an image or blurred-stream background. Works for
    // portrait (1080x1920) and landscape (upstream-sized) outputs alike.
    private static void BuildLayeredGraph(DestinationConfig dest, int srcW, int srcH, int outW, int outH, string delay, out string inputs, out string filterComplex)
    {
        inputs = "";
        var fc = new StringBuilder();

        int srcCount = dest.Layers.Count(l => l.Type == LayerType.Source);
        int revealCount = dest.Layers.Count(l => l.Type == LayerType.BackgroundReveal);

        // Background (bottom of the stack): custom image (gif = animated) or blurred stream.
        string bgFile = BackgroundImageFile(dest);
        bool blurBase = string.IsNullOrEmpty(bgFile);
        int nextInput = 1;
        if (!blurBase)
        {
            inputs += ImageInputArg(bgFile);
            fc.Append($"[{nextInput}:v]scale={outW}:{outH}[base];");
            nextInput++;
        }

        // Every consumer of the raw input needs its own copy: one per Source cut,
        // plus one for the blurred base when there is no background image.
        int consumers = srcCount + (blurBase ? 1 : 0);
        string InputCopy(int i) => consumers == 1 ? "[0:v]" : $"[katfg{i}]";
        if (consumers > 1)
        {
            var copies = string.Join("", Enumerable.Range(0, consumers).Select(i => $"[katfg{i}]"));
            fc.Insert(0, $"[0:v]split={consumers}{copies};");
        }
        if (blurBase)
        {
            fc.Append($"{InputCopy(consumers - 1)}scale={outW}:{outH}:force_original_aspect_ratio=increase,crop={outW}:{outH},boxblur=20:5[base];");
        }

        // Keep an untouched copy of the base for background reveals.
        int srcIndex = 0;
        string comp;
        if (revealCount > 0)
        {
            var copies = string.Join("", Enumerable.Range(0, revealCount).Select(i => $"[katbs{i}]"));
            fc.Append($"[base]split={1 + revealCount}[katcomp]{copies};");
            comp = "katcomp";
        }
        else
        {
            comp = "base";
        }
        int revealIndex = 0;

        int n = 0;
        foreach (var layer in dest.Layers)
        {
            (int ow, int oh, int ox, int oy) = OutputPx(layer, outW, outH);
            switch (layer.Type)
            {
                case LayerType.Source:
                {
                    (int sw, int sh, int sx, int sy) = SourcePx(layer, srcW, srcH);
                    fc.Append($"{InputCopy(srcIndex)}crop={sw}:{sh}:{sx}:{sy},scale={ow}:{oh}:flags=lanczos[kats{n}];");
                    srcIndex++;
                    fc.Append($"[{comp}][kats{n}]overlay={ox}:{oy}[katc{n}];");
                    comp = $"katc{n}";
                    break;
                }
                case LayerType.Image:
                {
                    if (string.IsNullOrWhiteSpace(layer.Path)) break;
                    string file = OverlayImageFile(layer);
                    inputs += ImageInputArg(file);
                    fc.Append($"[{nextInput}:v]scale={ow}:{oh}[katimg{n}];");
                    nextInput++;
                    fc.Append($"[{comp}][katimg{n}]overlay={ox}:{oy}[katc{n}];");
                    comp = $"katc{n}";
                    break;
                }
                case LayerType.Blur:
                {
                    fc.Append($"[{comp}]split=2[katpa{n}][katpb{n}];");
                    fc.Append($"[katpa{n}]crop={ow}:{oh}:{ox}:{oy},boxblur=20:5[katbl{n}];");
                    fc.Append($"[katpb{n}][katbl{n}]overlay={ox}:{oy}[katc{n}];");
                    comp = $"katc{n}";
                    break;
                }
                case LayerType.BackgroundReveal:
                {
                    fc.Append($"[katbs{revealIndex}]crop={ow}:{oh}:{ox}:{oy}[katrv{n}];");
                    revealIndex++;
                    fc.Append($"[{comp}][katrv{n}]overlay={ox}:{oy}[katc{n}];");
                    comp = $"katc{n}";
                    break;
                }
            }
            n++;
        }

        fc.Append($"[{comp}]setsar=1{delay}[v]");
        filterComplex = fc.ToString();
    }

    private static (int W, int H, int X, int Y) OutputPx(OutputLayer layer, int outW, int outH)
    {
        double w = Math.Clamp(layer.W, 0.005, 1);
        double h = Math.Clamp(layer.H, 0.005, 1);
        int pw = Math.Min(Math.Max(2, MakeEven((int)Math.Round(w * outW))), FloorEven(outW));
        int ph = Math.Min(Math.Max(2, MakeEven((int)Math.Round(h * outH))), FloorEven(outH));
        int px = Math.Clamp((int)Math.Round(Math.Clamp(layer.X, 0, Math.Max(0, 1 - w)) * outW), 0, Math.Max(0, outW - pw));
        int py = Math.Clamp((int)Math.Round(Math.Clamp(layer.Y, 0, Math.Max(0, 1 - h)) * outH), 0, Math.Max(0, outH - ph));
        return (pw, ph, px, py);
    }

    private static (int W, int H, int X, int Y) SourcePx(OutputLayer layer, int srcW, int srcH)
    {
        double w = Math.Clamp(layer.SrcW, 0.005, 1);
        double h = Math.Clamp(layer.SrcH, 0.005, 1);
        int pw = Math.Min(Math.Max(2, MakeEven((int)Math.Round(w * srcW))), FloorEven(srcW));
        int ph = Math.Min(Math.Max(2, MakeEven((int)Math.Round(h * srcH))), FloorEven(srcH));
        int px = Math.Clamp((int)Math.Round(Math.Clamp(layer.SrcX, 0, Math.Max(0, 1 - w)) * srcW), 0, Math.Max(0, srcW - pw));
        int py = Math.Clamp((int)Math.Round(Math.Clamp(layer.SrcY, 0, Math.Max(0, 1 - h)) * srcH), 0, Math.Max(0, srcH - ph));
        return (pw, ph, px, py);
    }

    // Normalizes the Custom portrait layout: fills in center-crop defaults for
    // untouched values and clamps everything so the crop stays 9:16 inside the
    // source and the stream stays inside the output frame. Single source of
    // truth for both the ffmpeg command and the Output Studio preview.
    public static (double CropX, double CropY, double CropW, double CropH, double FgX, double FgY, double FgScale) NormalizedCustomLayout(
        DestinationConfig dest, int srcW, int srcH)
    {
        srcW = Math.Max(2, srcW);
        srcH = Math.Max(2, srcH);
        double aspectFactor = (srcW / (double)srcH) * (16.0 / 9.0);

        double cropW = dest.CropW, cropX = dest.CropX, cropY = dest.CropY;
        if (cropW <= 0)
        {
            var c = ComputeCropRect(srcW, srcH);
            cropW = (double)c.CropW / srcW;
            cropX = (double)c.X / srcW;
            cropY = (double)c.Y / srcH;
        }
        double cropH = cropW * aspectFactor;
        if (cropH > 1)
        {
            cropH = 1;
            // Re-clamp: for a portrait source (aspectFactor < 1) the raw
            // 1/aspectFactor exceeds 1 and the Output Studio preview drew a
            // crop wider than the source frame (the server-side px math
            // clamps, so only the preview lied).
            cropW = Math.Min(1 / aspectFactor, 1);
        }
        cropX = Math.Clamp(cropX, 0, Math.Max(0, 1 - cropW));
        cropY = Math.Clamp(cropY, 0, Math.Max(0, 1 - cropH));

        double fgScale = dest.FgScale <= 0 ? 1 : Math.Clamp(dest.FgScale, 0.05, 1);
        double fgX = Math.Clamp(dest.FgX, 0, Math.Max(0, 1 - fgScale));
        double fgY = Math.Clamp(dest.FgY, 0, Math.Max(0, 1 - fgScale));

        return (cropX, cropY, cropW, cropH, fgX, fgY, fgScale);
    }

    // The portrait crop window the CenterCrop layout uses, in source pixels.
    // Same math as the generated crop filter, exposed so the Output Studio can
    // draw the exact same crop.
    public static (int CropW, int CropH, int X, int Y) ComputeCropRect(int srcW, int srcH)
    {
        srcW = Math.Max(2, srcW);
        srcH = Math.Max(2, srcH);
        // Round DOWN to even: rounding up (MakeEven) produced crops taller than
        // the source (608x1082 on 1920x1080, 406x722 on 1280x720) and ffmpeg
        // rejected the whole crop filter, killing CenterCrop destinations.
        int cropW = Math.Min(FloorEven(srcW), Math.Max(2, FloorEven(srcH * 9.0 / 16.0)));
        int cropH = Math.Min(FloorEven(srcH), Math.Max(2, FloorEven(cropW * 16.0 / 9.0)));
        int x = (srcW - cropW) / 2;
        int y = (srcH - cropH) / 2;
        return (cropW, cropH, x, y);
    }

    private static int MakeEven(int v) => v % 2 == 0 ? v : v + 1;

    // Even but never LARGER than the given bound - a crop/size rounded up could
    // exceed the frame it is cut from and make ffmpeg reject the filter.
    private static int FloorEven(double v)
    {
        int i = (int)Math.Round(v);
        return i - (i % 2);
    }
}
