using System.Text;
using KatStreamToolkit.Models;

namespace KatStreamToolkit.Services;

public static class RelayConfigGenerator
{
    public static string GenerateNginxConf(AppConfig cfg, bool includeKeys = true)
    {
        var up = cfg.Upstream;
        var sb = new StringBuilder();

        sb.AppendLine("# Generated by KAT's Streaming Toolkit - regenerate from the app after changing destinations.");
        sb.AppendLine("# NOTE: this file contains your platform stream keys. Never commit it publicly.");
        sb.AppendLine("worker_processes auto;");
        sb.AppendLine("error_log /var/log/nginx/error.log warn;");
        sb.AppendLine("pid /run/nginx.pid;");
        sb.AppendLine();
        sb.AppendLine("events {");
        sb.AppendLine("    worker_connections 1024;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("load_module /usr/lib/nginx/modules/ngx_rtmp_module.so;");
        sb.AppendLine();
        sb.AppendLine("rtmp {");
        sb.AppendLine("    server {");
        sb.AppendLine("        listen 1935;");
        sb.AppendLine("        chunk_size 4096;");
        sb.AppendLine();
        sb.AppendLine("        application live {");
        sb.AppendLine("            live on;");
        sb.AppendLine("            record off;");
        sb.AppendLine("            meta copy;");
        sb.AppendLine("            drop_idle_publisher 30s;");
        sb.AppendLine();

        var passthrough = cfg.Destinations.Where(d => d.Enabled && d.Orientation == Orientation.Landscape).ToList();
        var processed = cfg.Destinations.Where(d => d.Enabled && d.Orientation == Orientation.Portrait).ToList();

        if (passthrough.Count == 0 && processed.Count == 0)
            sb.AppendLine("            # (no destinations enabled yet - enable some in the toolkit)");

        foreach (var dest in passthrough)
        {
            sb.AppendLine($"            # {dest.Name}");
            sb.AppendLine($"            push \"{Url(dest, includeKeys)}\";");
            sb.AppendLine();
        }

        foreach (var dest in processed)
        {
            sb.AppendLine($"            # {dest.Name} ({dest.PortraitStyle})");
            sb.AppendLine($"            exec_push {BuildFfmpegArgs(up, dest, includeKeys)};");
            sb.AppendLine();
        }

        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string Url(DestinationConfig dest, bool includeKeys = true)
        => $"{dest.IngestUrl.TrimEnd('/')}/{(includeKeys ? dest.StreamKey : SecretsStore.MaskKey)}";

    private static string BuildFfmpegArgs(UpstreamConfig up, DestinationConfig dest, bool includeKeys)
    {
        int srcW = Math.Max(2, up.Width);
        int srcH = Math.Max(2, up.Height);
        string pull = $"rtmp://127.0.0.1:1935/live/$name";
        string output = Url(dest, includeKeys);
        int gop = Math.Max(1, up.Fps * Math.Max(1, dest.KeyframeSeconds));
        string audio = $"-c:a aac -b:a {dest.AudioBitrateKbps}k -ar 44100";
        string video = $"-c:v libx264 -preset veryfast -b:v {dest.VideoBitrateKbps}k -maxrate {dest.VideoBitrateKbps}k -bufsize {dest.VideoBitrateKbps * 2}k -pix_fmt yuv420p -g {gop} -sc_threshold 0";

        string filter = dest.PortraitStyle switch
        {
            PortraitStyle.CenterCrop => BuildCenterCropFilter(srcW, srcH),
            PortraitStyle.BlurredBackground => BuildBlurredFilter(srcW, srcH),
            _ => BuildCenterCropFilter(srcW, srcH),
        };

        if (dest.PortraitStyle == PortraitStyle.CenterCrop)
        {
            return $"\"/usr/bin/ffmpeg\" -hide_banner -loglevel warning -i \"{pull}\" -vf \"{filter}\" {video} {audio} -f flv \"{output}\"";
        }

        return $"\"/usr/bin/ffmpeg\" -hide_banner -loglevel warning -i \"{pull}\" -filter_complex \"{filter}\" -map \"[v]\" -map 0:a {video} {audio} -f flv \"{output}\"";
    }

    private static string BuildCenterCropFilter(int srcW, int srcH)
    {
        int cropW = MakeEven((int)Math.Round(srcH * 9.0 / 16.0));
        if (cropW > srcW)
            cropW = MakeEven((int)Math.Round(srcW * 16.0 / 9.0));
        int cropH = MakeEven((int)Math.Round(cropW * 16.0 / 9.0));
        int x = Math.Max(0, (srcW - cropW) / 2);
        int y = Math.Max(0, (srcH - cropH) / 2);
        return $"crop={cropW}:{cropH}:{x}:{y},scale=1080:1920:flags=lanczos,setsar=1";
    }

    private static string BuildBlurredFilter(int srcW, int srcH)
    {
        return "[0:v]split=2[bg][fg];" +
               "[bg]scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920,boxblur=20:5[bgb];" +
               "[fg]scale=1080:1920:force_original_aspect_ratio=decrease:flags=lanczos[fgs];" +
               "[bgb][fgs]overlay=(W-w)/2:(H-h)/2,setsar=1[v]";
    }

    private static int MakeEven(int v) => v % 2 == 0 ? v : v + 1;
}
