<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>KatStreamToolkit</RootNamespace>
    <AssemblyName>KatStreamToolkit</AssemblyName>
    <Version>0.1.0</Version>
    <Product>KAT's Streaming Toolkit</Product>
  </PropertyGroup>

</Project>
